substitutions:
  _SERVICE_NAME: bikeweatherdecision
  _REGION: europe-west1

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --source=.
      - --function=send_weather_email
      - --base-image=python313
      - --region=${_REGION}
      - --platform=managed
      - --service-account=bike-541@cis673-307121.iam.gserviceaccount.com
      - --cpu=1
      - --memory=512Mi
      - --concurrency=1
      - --timeout=60s
      - --min=0
      - --max=1
      - --set-secrets=gmail_username=gmail_username:latest,gmail_password=gmail_password:latest,weather_api=weather_api:latest
      - --no-allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
